-- El highlight de Treesitter para Elixir (.ex/.exs) ahora se activa
-- automáticamente desde lua/plugins/treesiter.lua (autocomando FileType,
-- rama `main`). El comando antiguo `:TSBufEnable highlight` ya no existe.
